import { Player, Position } from './types';

export const PLAYERS_DATA: Player[] = [
    {
        id: 1,
        name: 'Arda Güler',
        age: 17,
        position: Position.Midfielder,
        height: 176,
        weight: 70,
        bio: 'Teknik kapasitesi yüksek, oyun kurucu ve genç yaşına rağmen liderlik özellikleriyle öne çıkan bir orta saha oyuncusu. Duran toplarda etkilidir.',
        profileImageUrl: 'https://i.pravatar.cc/400?u=1',
        videoUrl: 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
        talentScore: 92,
        tags: ['Oyun Zekası', 'Teknik Kapasite', 'Pas Yeteneği', 'Dribbling', 'Şut Gücü'],
        country: 'Türkiye',
        countryCode: 'tr',
        status: 'active',
    },
    {
        id: 2,
        name: 'Leo Messi Jr.',
        age: 12,
        position: Position.Forward,
        height: 155,
        weight: 48,
        bio: 'Hızlı, çevik ve inanılmaz bir top kontrolüne sahip. Dar alanda adam eksiltebiliyor ve bitiriciliği çok yüksek. Geleceğin yıldız adayı.',
        profileImageUrl: 'https://i.pravatar.cc/400?u=2',
        videoUrl: 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
        talentScore: 88,
        tags: ['Hız', 'Çalım Yeteneği', 'Bitiricilik', 'Top Kontrolü'],
        country: 'Arjantin',
        countryCode: 'ar',
        status: 'active',
    },
    {
        id: 3,
        name: 'Can Yılmaz',
        age: 15,
        position: Position.Defender,
        height: 182,
        weight: 75,
        bio: 'Güçlü fiziği, doğru pozisyon alması ve hava topu hakimiyeti ile tanınan modern bir stoper. Oyun kurma becerisi de gelişmiş seviyede.',
        profileImageUrl: 'https://i.pravatar.cc/400?u=3',
        videoUrl: 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
        talentScore: 85,
        tags: ['Defansif Müdahale', 'Hava Topu Hakimiyeti', 'Güç', 'Pozisyon Alma'],
        country: 'Almanya',
        countryCode: 'de',
        status: 'active',
    },
    {
        id: 4,
        name: 'Emre Kaya',
        age: 16,
        position: Position.Goalkeeper,
        height: 188,
        weight: 78,
        bio: 'İnanılmaz reflekslere ve bire bir pozisyonlarda yüksek başarı oranına sahip bir kaleci. Yan toplarda güven veriyor ve ayaklarını iyi kullanıyor.',
        profileImageUrl: 'https://i.pravatar.cc/400?u=4',
        videoUrl: 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
        talentScore: 89,
        tags: ['Refleks', 'Liderlik', 'Uzun Pas', 'Pozisyon Alma'],
        country: 'Türkiye',
        countryCode: 'tr',
        status: 'active',
    },
];

export const POPULAR_TAGS: string[] = [
  'Hız',
  'Dribbling',
  'Şut Gücü',
  'Pas Yeteneği',
  'Dayanıklılık',
  'Teknik Kapasite',
  'Oyun Zekası',
  'Hava Topu Hakimiyeti',
  'Defansif Müdahale',
  'Bitiricilik',
  'Çalım Yeteneği',
  'Uzun Pas',
  'Top Kontrolü',
  'Markaj',
  'Pozisyon Alma',
  'Agresiflik',
  'Liderlik',
  'Takım Oyunu',
];